### ISSUE TITLE
how to validation insert and pagination in manage?

### ISSUE THREAD

**Issue by andridgitalbox** [pooyamb/wpsamplecrudplugin#2]
helloo sir..i found dificult validation insert data and pagination ...please share sir..thanks

**Comment by pooyamb** [comment]
Hi again,

I will add pagination in this week if you want,
BTW you can get your hand dirty and add it and send a pull request.
if you have any other question, send me a mail with more details, so I can help you.

Thanks

**Comment by andridgitalbox** [comment]
Hi..sir
Thanks sir your respon :+1:  i will waiting updates 
ok iam send email now...thanks
